//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularDemoCrud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string productName { get; set; }
        public string productCode { get; set; }
        public string releaseDate { get; set; }
        public double price { get; set; }
        public string description { get; set; }
        public double starRating { get; set; }
        public string imageUrl { get; set; }
        public int productId { get; set; }
    }
}
